#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL


// VERTEX ATTRIBUTES: layout(location = _____)

#define POSITION_ATTRIB_LOCATION			0
#define NORMAL_ATTRIB_LOCATION				1
#define TEXCOORD_ATTRIB_LOCATION			2
#define COLOR_ATTRIB_LOCATION				3
#define INSTANCE_POSITION_ATTRIB_LOCATION	4
#define INSTANCE_FORWARD_ATTRIB_LOCATION	5


// SHADER UNIFORMS: layout(location = _____)

#define MVP_UNIFORM_LOCATION				0
#define MV_UNIFORM_LOCATION					1
#define MV_INV_TRANS_UNIFORM_LOCATION		2
#define LIGHTDIR_UNIFORM_LOCATION			3


// TEXTURE UNITS: layout(binding = _____)

#define DIFFUSE_TEXTURE_BINDING				0
#define SPECULAR_TEXTURE_BINDING			1
#define EMISSIVE_TEXTURE_BINDING			2


#endif // PREAMBLE_GLSL