#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

#define POSITION_ATTRIB_LOCATION 0
#define NORMAL_ATTRIB_LOCATION 1
#define TEXCOORD_ATTRIB_LOCATION 2

#define MVP_UNIFORM_LOCATION 0
#define MV_UNIFORM_LOCATION 1
#define LIGHTDIR_UNIFORM_LOCATION 2

#define DIFFUSE_TEXTURE_BINDING 0

#endif // PREAMBLE_GLSL